### ISSUE TITLE
User can view a post content item by ID

### ISSUE THREAD

**Issue by richiebotteri** [richiebotteri/meetzy#23]
### To-do

- [ ] create a function that gets posts ID from the browser URL params
- [ ] Than uses it to make a fetch request to get the post with that ID
- [ ] Than display it on its own singular post-page
